#!/bin/bash
#
#
#
template_name="default1"

decho "Working in template $template_name..."
source ./$template/tags-init
source ./$template/pages
source ./$template/posts
source ./$template/index
source ./$template/rss
decho "template building complete."
