#!/bin/bash
# STYLE
# 
#
#

#

cat << EOF
<style>
body {
	color: green;
	background-color:#000000;
	font-family: Verdana, Tahoma, sans-serif, Arial; 
	margin-left: 0px;	
	margin-top: 5px;	
	margin-right: 0px;	
	margin-bottom: 15px;
	font-size: 13pt;
	}
h1   {color:blue}
p    {color:green}
#main {
	background-color: #efe0b2;
	width: 800px;
	text-align: center;
	margin-left: auto;
	margin-right: auto;
	margin-top: 0px; 
  border-radius: .25em;
padding: 0px 0px 0x 0px;

}
sup {
  top: -.5em;
}
sub {
  bottom: -.25em;
}
img {
  border: 0;
}
p {
font-size: 1em;
padding: 0px 0px 0x 0px;
}
a {
text-decoration: none;
outline: none;
}
#title
{
    border: 0px solid #000;
    font-size: 300%;
    border-radius: .25em;
    text-align: center;
    padding: .2em .6em .3em;
    background-color: #999;
    color: #fff;
    width: 670px;
    align-content: center;
    text-align: center;
    padding: 0px 0px 0x 0px;
    margin-bottom: 12px;
    margin-top: 22px;
}

.tag{
  border: 1px solid #000;
  background-color: #999;
  display: inline;
  padding: .2em .6em .3em;
  font-size: 75%;
  line-height: 0.9;
  color: #fff;
  text-align: center;
  white-space: nowrap;
  vertical-align: baseline;
  border-radius: .25em;
  display: inline-block;
  margin-bottom: 5px;
  font-weight: bold;
}
.tag:hover{
     background-color: #fff;
	  color: #000;
}
.page{
  color: #blue;
  text-align: center;
  white-space: nowrap;
  vertical-align: baseline;
  border-radius: .25em;
  display: inline-block;
  padding: .2em .6em .2em;
  border: 0px solid #000;
}
.page:hover{
  background-color: #666;
  color: #ccc;
}
.page-sel{
  color: #blue;
  text-align: center;
  white-space: nowrap;
  vertical-align: baseline;
  border-radius: .25em;
  display: inline-block;
  padding: .2em .7em .2em;
  border: 0px solid #000;
  background-color: #666;
  color: #ccc;
}
.message 
{
   background-color: #232323;
   width: 630px;
   text-align: justify;
   white-space: wrap;
   vertical-align: baseline;
   display: inline-block;
   padding: .3em 3em .3em;
   border: 0px solid #000;
   margin-left: auto;
   margin-right: auto;
   margin-top: 0px; 
   border-radius: .5em;
   font-family: Verdana, Tahoma, sans-serif, Arial; 
   font-size: 12pt;
   color: #8699A0;
   text-shadow: 0 0 3px #758890;
   box-shadow: 0 0 10px rgba(0,0,0,0.8);
}
.message:hover
{
   background-color: #191919;
}  
hr {
  border:none;
  border-top:1px dotted #f00;
  color:#bbb;
  background-color:#aaa;
  height:1px;
  width:90%;
}
</style>
EOF
