#!/bin/bash
#
# generating tags

#source etc/config
#source lib/comm

tags_map=$cache/tags-map
tags_index=$cache/tags-index

#generate tags-map
#generate tags-index
#generate per-tags-pages

mktagmap()
{
decho "Creating tags map..."
if [ ! -d "$cache" ]; then
	decho "cache dir $cache creating."
	mkdir -p $cache
fi
echo -n "" > $tags_map

POSTS_LIST=$(find $posts/ -type f -printf "%f ")
for post in $POSTS_LIST; do
	TAGLIST=$(cat $posts/$post|grep "{{{ tags " | sed -e 's|{{{ tags ||;s|}}}||;s| ||g' | sort | head -n 1)
	# taglist - must be comma separated like : Linux,Kernel,Misc
	name=$(cat $posts/$post|grep "{{{ name" | sed -e 's|{{{ name ||;s|}}}||;s| ||g' | sort | head -n 1)
	[ -z "$name" ] && name=$post
	if [ ! -z "$TAGLIST" ]; then
		IFS=','
		for tag in $(echo $TAGLIST| tr "\n" ","); do
			decho "  adding TAG:"$tag" with post->"$post
			echo "$tag,$post,$name" >> $tags_map
		done
		IFS=' '
	fi
done
}

mktagindex()
{
	echo -n "" > $tags_index
	decho "Creating tags index..."
	for tag in $(cat $tags_map|awk -F"," '{print $1}' | sort | uniq | tr "\n" " "); do
		#atag=$(echo "$tag_line" | awk -F"," '{print $1}')
		echo "<a class=\"tag\" href=\"tag_"$tag".html\">"$tag"</a>" >> $tags_index
	done
	decho "complete."
}


mktagpage()
{
	targettag=$1
        PAGE=$targettag
        ./$template/html-begin
        ./$template/head $PAGE
        ./$template/style
        ./$template/table-main
        source ./$template/pages-list
        source ./$template/tags
	let c=0
	echo "<div class=message><pre>"
	echo "Posts market by tag \"$targettag\":<br><br>"
	IFS=$'\n'
        for tag_line in $(cat $tags_map| grep "$targettag"); do
                tag=$(echo "$tag_line" | awk -F"," '{print $1}')
                page=$(echo "$tag_line"| awk -F"," '{print $2}')
		if [ ! -z "$tag" ]; then
	                tagpage=$page".html"
		        date=$(grep -i "{{{ date" $posts/$page | awk -F" " '{print $3}' | head -n 1)
			[ -z "$date" ] && date=$(stat -c "%y" $posts/$page | awk -F"." '{print $1}')
			name=$(echo "$tag_line"| awk -F"," '{print $3}')
			[ -z "$name" ] && name=$page
			count=$(printf "0x%0.4x\n" $c)
			echo $count"] <b><a class=\"linkpage\" href=\"$tagpage\">$name</a></b><small>($date)</small>"
			let c=c+1
		fi
	done
	IFS=' '
	echo "</pre></div>"
        ./$template/footer-pre
        ./$template/footer
        ./$template/html-end

}

mkpertagpages()
{
        decho "Creating tags pages..."
	IFS=' '
	for tag in $(cat $tags_map | awk -F"," '{print $1}' | sort | uniq| tr "\n" " "); do
		decho "Generating tag page $tag"
		if [ ! -z "$tag" ]; then
                        decho "--> tag \"$tag\""
                        mktagpage $tag >>  $out"/tag_"$tag".html"
                fi
	done
       ## for tag_line in $(cat $tags_map); do
       ##         tag=$(echo "$tag_line" | awk -F"," '{print $1}')
       ##         page=$(echo "$tag_line"| awk -F"," '{print $1}')
       ## 	if [ ! -z "$tag" ]; then
       ##                 decho "--> tag \"$tag\""
       ## 		mktagpage $tag >>  $out"/tag_"$tag".html"
       ## 	fi
       ## done
        decho "complete."
}

mktagmap
mktagindex
mkpertagpages

#exit
decho "tag processing complete"
